(function () {
  const data = window.siteData;

  data.piBio = {
    en: [
      "Jie Su is a professor at the College of the Environment and Ecology and the Institute for Ocean and Coastal Development, Xiamen University. She is affiliated with the National Observation and Research Station for the Taiwan Strait Marine Ecosystem, the Key Laboratory of the Coastal and Wetland Ecosystem of the Ministry of Education, and the Fujian Provincial Key Laboratory for Coastal Ecology and Environmental Studies. She is also a Visiting Researcher at the Institute for Future Initiatives, The University of Tokyo.",
      "She received her BSc. from Fudan University, MSc. in Environmental Management from Xiamen University, and PhD in Sustainability Science from The University of Tokyo. Before joining Xiamen University, she was a Project Assistant Professor at the Institute for Future Initiatives, The University of Tokyo.",
      "Her research applies social-ecological systems and ecological economics approaches to examine interactions between human societies and natural ecosystems under global environmental change. It develops integrated solutions for coastal conservation and restoration, particularly in mangrove ecosystems, linking biodiversity conservation, climate action, economic development, and human well-being.",
      "She serves as an expert for the IPBES Spatial Planning and Connectivity Assessment, has served as a reviewer for the European Partnership BIODIVERSA+, and is an Editor of Sustainability Science."
    ],
    zh: [
      "苏婕，厦门大学环境与生态学院、海洋与海岸带发展研究院教授、博士生导师，海洋生物地球化学全国重点实验室、福建台湾海峡生态系统国家野外科学观测研究站和福建省海陆界面生态环境重点实验室固定科研人员，东京大学未来愿景研究中心客座研究员。",
      "她本科毕业于复旦大学环境科学（环境管理）专业，硕士毕业于厦门大学环境科学与工程（环境管理）专业，博士毕业于东京大学可持续科学专业。加入厦门大学前，她曾任东京大学未来愿景研究中心特任助理教授。",
      "她的研究运用社会-生态系统与生态经济学方法，探究全球环境变化背景下人类社会与自然生态系统之间复杂的相互作用。研究旨在构建海岸带保护与修复的综合解决方案，尤其聚焦红树林生态系统，通过统筹生物多样性保护、气候变化减缓与适应、经济发展和人类福祉，实现可持续发展。",
      "她现任生物多样性和生态系统服务政府间科学政策平台（IPBES）空间规划与连通性评估专家，欧盟生物多样性跨国多边合作计划（BIODIVERSA+）项目评审专家，以及 Sustainability Science 期刊编委。"
    ]
  };

  data.researchThemes = [
    {
      en: { title: "Social-Ecological System Sustainability", tag: "Coupled systems", summary: "We examine interactions between society and ecosystems in coastal and marine settings, with particular attention to mangroves, coastal communities, and governance.", details: ["Coastal social-ecological systems", "Coastal ecosystems", "Ecosystem services and human well-being"] },
      zh: { title: "可持续社会-生态系统", tag: "人地耦合", summary: "研究海洋与海岸带社会系统和生态系统之间的相互作用，重点关注红树林、沿海社区与治理机制。", details: ["海岸带社会-生态系统", "滨海生态系统", "生态系统服务与人类福祉"] }
    },
    {
      en: { title: "Ecological Economics", tag: "Decision support", summary: "We apply economic and decision-analysis approaches to understand policy trade-offs, public acceptability, restoration costs, and sustainable management options.", details: ["Ecosystem-service valuation", "Cost-benefit analysis", "Policy trade-offs"] },
      zh: { title: "生态经济学", tag: "决策支持", summary: "运用生态经济学与决策分析方法，评估政策权衡、公众接受度、修复成本与可持续管理路径。", details: ["生态系统服务价值评估", "成本—效益分析", "政策权衡"] }
    },
    {
      en: { title: "Climate Change Adaptation and Environmental Management", tag: "Adaptation", summary: "We assess adaptation pathways, nature-based solutions, and environmental management strategies for coastal regions facing climate risks.", details: ["Climate adaptation", "Nature-based solutions", "Environmental management"] },
      zh: { title: "气候变化适应与环境管理", tag: "气候适应", summary: "评估面向气候风险的海岸带适应路径、基于自然的解决方案与环境管理策略。", details: ["气候变化适应", "基于自然的解决方案", "环境管理"] }
    },
    {
      en: { title: "Coastal Spatial Planning", tag: "Spatial planning", summary: "We develop evidence-based spatial planning approaches that integrate ecosystem conservation, coastal livelihoods, climate resilience, and sustainable blue-economy development across the land-sea interface.", details: ["Restoration and conservation planning", "Land-sea coordination", "Spatial decision support"] },
      zh: { title: "海岸带空间规划", tag: "空间规划", summary: "面向陆海交错带开展基于证据的空间规划研究，统筹生态保护、沿海生计、气候韧性与蓝色经济可持续发展。", details: ["保护与修复空间规划", "陆海统筹", "空间决策支持"] }
    }
  ];

  const person = (nameEn, nameZh, roleEn, roleZh, majorEn, majorZh, directionEn, directionZh, bioEn, bioZh, image) => ({ nameEn, nameZh, roleEn, roleZh, majorEn, majorZh, directionEn, directionZh, bioEn, bioZh, image, portrait: { scale: "1.42", origin: "50% 30%" } });
  data.peopleGroups = [
    { en: "Postdoctoral researcher", zh: "博士后", members: [person("Fan Yang", "杨帆", "Postdoctoral researcher", "博士后", "Resources and Environment", "资源与环境", "Environmental remote sensing", "环境遥感", "Fan Yang received her PhD in Resources and Environment from Sun Yat-sen University. Her work examines vegetation remote sensing, urban ecology, and disaster-related studies, with a focus on vegetation resilience in tropical and subtropical urban regions.", "杨帆毕业于中山大学资源与环境专业，获博士学位。她主要从事环境遥感研究，关注植被遥感、城市生态与灾害事件，重点探究热带—亚热带城市植被恢复力的时空变化及其气候变化和人类活动驱动机制。", "assets/fan-yang-2026.jpeg")] },
    { en: "PhD students", zh: "博士研究生", members: [
      person("Huilin Lai", "赖慧琳", "PhD student, 2025-", "2025级博士研究生", "Environmental Management", "环境管理", "Mangrove social-ecological systems", "红树林社会—生态系统", "Huilin Lai holds a Master's degree in Economics from Ningbo University. Her research examines mangrove ecosystems, coastal livelihoods, environmental governance, ecosystem services, and social-ecological resilience.", "赖慧琳拥有宁波大学经济学硕士学位。她关注红树林生态系统、沿海生计与环境治理之间的相互作用，重点研究人类活动和管理干预对生态系统服务、生计福祉及社会—生态系统韧性的影响。", "assets/huilin-lai-2026.jpeg"),
      person("Zelong Ma", "马泽龙", "PhD student, 2026-", "2026级博士研究生", "Environmental Management", "环境管理", "Human-environment coupling across the land-sea interface", "陆海界面人地耦合系统", "Zelong Ma received his Master's degree from the Guangzhou Institute of Geochemistry, Chinese Academy of Sciences. He studies human-environment coupling and telecoupling across the land-sea interface, with a focus on the Jiulong River-Xiamen Bay region.", "马泽龙毕业于中国科学院广州地球化学研究所，获硕士学位。他关注陆海界面人地耦合系统与远程耦合，重点研究九龙江—厦门湾区域社会经济系统与生态环境系统的耦合关系。", "assets/zelong-ma-2026.jpeg"),
      person("Shouxiang Sun", "孙守祥", "PhD student, 2026-", "2026级博士研究生", "Marine Affairs", "海洋事务", "Coastal blue-carbon ecosystem management", "海岸带蓝碳生态系统管理", "Shouxiang Sun holds a BSc in Economics from Xiamen University and completed a Statistics minor at WISE. His research focuses on climate change, environmental economics, and management strategies for coastal blue-carbon ecosystem conservation and restoration.", "孙守祥本科毕业于厦门大学经济学专业，并完成王亚南经济研究院统计学（数理）辅修课程。他关注气候变化、环境经济学和海岸带综合管理，当前聚焦以经济学视角探索兼顾生态效益与经济效率的蓝碳生态系统保护修复方案。", "assets/shouxiang-sun-2026.jpeg")
    ] },
    { en: "Master students", zh: "硕士研究生", members: [
      person("Yixin Chen", "陈奕欣", "Master student, 2025-", "2025级硕士研究生", "Marine Affairs", "海洋事务", "Integrated mangrove-aquaculture systems", "红树林—水产养殖耦合系统", "Yixin Chen studies integrated mangrove-aquaculture systems, coastal environmental policy, and governance. Her work compares ecological and socioeconomic outcomes across aquaculture and restoration models.", "陈奕欣关注红树林—水产养殖耦合系统、海岸带环境政策与治理，重点比较不同种养耦合、传统养殖和红树林修复模式的生态与社会经济效应。", "assets/yixin-chen-2026.jpeg"),
      person("Qingcheng Liu", "刘青成", "Master student, 2025-", "2025级硕士研究生", "Environmental Management", "环境管理", "Social dimensions of ecological restoration", "生态修复的社会维度", "Qingcheng Liu studies ecological restoration, social-ecological systems, nature conservation, and community well-being. His current work examines restoration assessment and livelihoods around the Zhangjiang Estuary Mangrove National Nature Reserve.", "刘青成关注生态修复、社会—生态系统、自然保护与社区福祉。当前研究从社会—生态视角理解和评估修复行动，并以漳江口红树林国家级自然保护区及周边社区为案例探讨社区生计与福祉。", "assets/qingcheng-liu-2026.jpeg"),
      person("Feibin Huang", "黄沸彬", "Master student, 2026-", "2026级硕士研究生", "Marine Affairs", "海洋事务", "Ecosystem-service valuation", "生态系统服务价值评估", "Feibin Huang holds a Bachelor of Management from Nanjing University of Finance and Economics. His interests include ecosystem-service valuation, marine resource management, and sustainable development.", "黄沸彬毕业于南京财经大学，获管理学学士学位，曾开展生态系统服务价值评估研究。他关注生态系统服务价值、海洋资源管理及其与可持续发展的交叉领域。", "assets/feibin-huang-2026.jpeg"),
      person("Tianlei Pu", "蒲田雷", "Master student, 2026-", "2026级硕士研究生", "Environmental Management", "环境管理", "Coastal wetland ecology and cultural ecosystem services", "滨海湿地生态与文化生态系统服务", "Tianlei Pu holds a BSc in Artificial Intelligence from Hunan University of Technology and Business. His current work examines the spatiotemporal patterns of mangrove cultural ecosystem services and human well-being.", "蒲田雷本科毕业于湖南工商大学人工智能专业。他关注滨海湿地生态、人地耦合系统与生态系统服务，当前研究红树林文化生态系统服务与人类福祉的时空分异特征。", "assets/tianlei-pu-2026.jpeg"),
      person("Huiru Qiang", "强慧如", "Master student, 2026-", "2026级硕士研究生", "Environmental Management", "环境管理", "Mangrove ecotourism and human well-being", "红树林生态旅游与人类福祉", "Huiru Qiang holds a Bachelor's degree in Tourism Management from Dalian University. Her research explores mangrove cultural ecosystem services, ecotourism, local livelihoods, and coastal community well-being.", "强慧如本科毕业于大连大学旅游管理专业。她关注红树林文化生态系统服务、人类福祉和生态旅游，重点探讨红树林保护、社区生计、可持续旅游和沿海社区福祉之间的关系。", "assets/huiru-qiang-2026.jpeg"),
      person("Sherlon Juntillo Sulapas", "Sherlon Juntillo Sulapas", "Master student, 2026-", "2026级硕士研究生", "Marine Affairs", "海洋事务", "Marine and coastal conservation", "海洋与海岸带保护", "Sherlon Juntilo Sulapas holds a BSc in Biology, majoring in Ecology, from Visayas State University, Philippines. He studies marine and coastal conservation, blue carbon, climate change, biodiversity, and sustainable coastal management.", "Sherlon Juntilo Sulapas 本科毕业于菲律宾维萨亚斯大学生态学专业。他关注海洋与海岸带保护、蓝碳、气候变化、生物多样性、海洋政策与可持续海岸带管理。", "assets/sherlon-sulapas-2026.jpeg"),
      person("Yuwei Zhang", "张玉玮", "Master student, 2026-", "2026级硕士研究生", "Environmental Management", "环境管理", "Ecological restoration and biodiversity", "生态修复与生物多样性", "Yuwei Zhang holds a BSc (Hons) in Applied Economics from The Chinese University of Hong Kong, Shenzhen. She studies ecological restoration, biodiversity conservation, and the costs and economic benefits of mangrove restoration.", "张玉玮本科毕业于香港中文大学（深圳）应用经济学专业，获经济学荣誉学士学位。她关注生态修复、红树林社会经济效益和生物多样性保护，重点研究修复成效、成本与经济效益。", "assets/yuwei-zhang-2026.jpeg")
    ] },
    { en: "Undergraduate students", zh: "本科生", members: [
      person("Mingzhe Li", "李明哲", "Undergraduate student, 2024-", "2024级本科生", "Environmental Science", "环境科学", "Mangrove social-ecological-economic assessment", "红树林社会—生态—经济评估", "Mingzhe Li studies coastal mangrove ecosystems and social-ecological-economic coupled-system assessment. He leads a university Student Innovation Training Program on integrated mangrove-aquaculture systems.", "李明哲关注滨海红树林生态系统及社会—生态—经济耦合系统评估，现主持校级大学生创新训练计划，开展红树林种养耦合模式的生态、经济和社会效益综合评估。", "assets/mingzhe-li-2026.jpeg"),
      person("Ruiyang Zhong", "钟瑞阳", "Undergraduate student, 2024-", "2024级本科生", "Ecology", "生态学", "Blue carbon and ecological planning", "蓝碳与生态规划", "Ruiyang Zhong is an undergraduate in the Ecology Excellence Program at Xiamen University. He studies ecosystem carbon sinks, blue carbon, urban ecological planning, environmental economics, and integrated mangrove-aquaculture systems.", "钟瑞阳是厦门大学生态学强基班本科生。他关注生态系统碳汇、蓝碳、城市生态规划与环境经济，以及红树林种养耦合模式中生态、经济和社会效益的协同与权衡。", "assets/ruiyang-zhong-2026.jpeg"),
      person("Haochen Yang", "杨昊宸", "Undergraduate student, 2025-", "2025级本科生", "Ecology", "生态学", "Ecosystem management and sustainability", "生态系统管理与可持续发展", "Haochen Yang is an undergraduate student in Ecology at Xiamen University. His current work assesses the ecological, economic, and social outcomes of integrated mangrove-aquaculture systems.", "杨昊宸是厦门大学生态学专业本科生。他关注生态系统管理、可持续发展，以及红树林种养耦合模式的生态、经济与社会效益评估。", "assets/haochen-yang-2026.jpeg")
    ] },
    { en: "Research assistants", zh: "研究助理", members: [
      person("Jinhao Li", "李锦豪", "Research Assistant", "研究助理", "Environmental Management", "环境管理", "Fisheries sustainability and climate economics", "渔业可持续发展与气候经济学", "Jinhao Li holds a Master's degree in Environmental Management from Xiamen University and is preparing for doctoral studies. His current research examines fuel substitution and low-carbon transition pathways in fisheries.", "李锦豪拥有厦门大学环境管理硕士学位，现正准备攻读博士学位。他关注渔业可持续发展与气候变化经济学，当前研究渔船燃料替代和渔业低碳转型路径。", "assets/jinhao-li-2026.jpeg"),
      person("Yuhang Peng", "彭宇航", "Research Assistant", "研究助理", "Marine Resources and Environment", "海洋资源与环境", "Marine ecological-product valuation", "海洋生态产品价值核算", "Yuhang Peng holds a Master's degree in Marine Resources and Environment from Guangdong Ocean University. He supports lab administration and works with ArcGIS and marine ecological-product valuation.", "彭宇航拥有广东海洋大学海洋资源与环境硕士学位。他负责课题组日常事务管理，熟悉 ArcGIS 和海洋生态产品价值核算。", "assets/yuhang-peng-2026.jpeg")
    ] }
  ];

  data.projects = [
    { category: "restoration", period: "2027-2030", roleEn: "PI", roleZh: "主持", titleEn: "Assessing net benefits and instability mechanisms for spatial optimization of mangrove restoration", titleZh: "典型红树林修复模式净效益、不稳定机制与空间优化路径", funderEn: "NSFC Science Fund General Program", funderZh: "国家自然科学基金面上项目", summaryEn: "This project examines the net benefits, instability mechanisms, and spatial optimization pathways of representative mangrove restoration models in Fujian, China. It will develop an integrated framework for evaluating social-ecological outcomes and support spatial prioritization, adaptive planning, and governance.", summaryZh: "本项目以福建省典型红树林修复模式为对象，研究其社会—生态净效益、不稳定机制与空间优化路径。项目将构建综合评估与模拟框架，为红树林修复的空间优先排序、适应性规划与治理决策提供科学依据和模型工具。" },
    { category: "bluecarbon", period: "2026-2028", roleEn: "Co-PI", roleZh: "参与", titleEn: "Zhangjiang Estuary Mangrove Carbon Sink Enhancement and Ecological Health Synergistic Demonstration", titleZh: "漳江口红树林增汇与生态健康协同增效示范", funderEn: "Key Project, National Key Laboratory of Marine Biogeochemistry", funderZh: "厦门大学海洋生物地球化学全国重点实验室揭榜挂帅重点项目", summaryEn: "This project evaluates the social-ecological outcomes of mangrove restoration in the Zhangjiang Estuary, with particular attention to carbon-sink enhancement and ecosystem health. It examines how invasive-plant removal and ecological restoration can improve ecosystem services and community well-being.", summaryZh: "本项目评估漳江口红树林修复的社会—生态效益，重点关注红树林增汇与生态健康的协同提升。研究将探讨入侵植物清除与生态恢复工程如何改善生态系统服务，并进一步影响周边社区的环境福祉感知与多维福祉水平。" },
    { category: "aquaculture", period: "2025-2027", roleEn: "PI", roleZh: "主持", titleEn: "Integrated social-ecological approaches to coastal ecosystem restoration and sustainability", titleZh: "人地耦合的海岸带生态修复与可持续发展", funderEn: "NSFC Science Fund Program for Excellent Young Scientists Overseas", funderZh: "国家高层次人才青年项目", summaryEn: "This project investigates human-nature coupling mechanisms in coastal ecosystem restoration and sustainable development. It compares ecological, economic, and social outcomes across alternative mangrove conservation, restoration, and pond-aquaculture scenarios to identify pathways that balance ecosystem protection with local livelihoods.", summaryZh: "本项目研究海岸带生态修复与可持续发展中的人地耦合机制，比较不同红树林保护修复与围塘养殖发展情景下的生态、经济和社会效益，识别兼顾生态保护与地方生计的协同发展路径和最优模式。" },
    { category: "ecotourism", period: "2025-2027", roleEn: "PI", roleZh: "主持", titleEn: "Ecological-Social Coupling Mechanisms and Optimized Pathways for Mangrove Ecosystems in the Minnan Delta", titleZh: "闽三角红树林生态—社会耦合机制与优化路径构建", funderEn: "President Foundation of Xiamen University", funderZh: "厦门大学校长基金", summaryEn: "This project investigates ecological-social coupling in mangrove ecosystems across the Minnan Delta, integrating ecological characteristics with cultural ecosystem services. It develops an assessment framework to identify coupling mechanisms, synergistic development pathways, and their spatial patterns.", summaryZh: "本项目以闽三角为研究区域，探究红树林生态系统的生态—社会耦合机制，统筹生态特征与文化生态系统服务。研究将构建评估框架，识别不同类型红树林的耦合机制、协同增效路径及其空间分布特征。" }
  ];

  data.news = [
    { dateEn: "August 23-29, 2026", dateZh: "2026年8月23-29日", categoryEn: "Author meeting", categoryZh: "评估作者会议", titleEn: "Jie Su attends the second author meeting of the IPBES spatial planning and connectivity assessment", titleZh: "苏婕参加 IPBES 空间规划与连通性评估第二次作者会议", summaryEn: "From 24 to 28 August 2026, Professor Jie Su attended the second author meeting of the IPBES Spatial Planning and Connectivity Assessment in Monteverde, Costa Rica, in her capacity as a review editor. Participants reviewed more than 5,000 comments from governments and stakeholders on the first-order draft and discussed revisions for the second draft of the assessment.", summaryZh: "2026年8月24-28日，苏婕以评审编辑身份赴哥斯达黎加蒙特韦尔德参加 IPBES 空间规划与连通性评估第二次作者会议。与会专家集中审阅了各国政府和利益相关方针对评估报告一稿提交的5,000余条意见，并就报告二稿的修订方向进行了讨论。", images: [] },
    { dateEn: "August 9-16, 2026", dateZh: "2026年8月9-16日", categoryEn: "Summer School", categoryZh: "暑期学校", titleEn: "SESuS Lab attends the Summer School on Geography and Sustainability 2026", titleZh: "课题组参加2026年地理学与可持续性暑期学堂", summaryEn: "From 9 to 16 August 2026, Zelong Ma attended the 2026 Summer School on Geography and Sustainability at Beijing Normal University. The programme focused on frontiers in telecoupling and metacoupling research for global sustainability challenges; as a group leader, he also organised the project Understanding Cross-Regional Flood Impacts through the Telecoupling Framework.", summaryZh: "2026年8月9-16日，马泽龙参加了北京师范大学地理科学学部主办的2026年地理学与可持续性暑期学堂。学堂聚焦远程耦合与全程耦合研究前沿及全球可持续发展挑战；他作为小组组长，组织开展了跨区域洪水影响远程耦合框架项目。", images: ["assets/news-geography-summer-1.jpeg", "assets/news-geography-summer-2.jpeg", "assets/news-geography-summer-3.jpeg", "assets/news-geography-summer-4.jpeg", "assets/news-geography-summer-5.jpeg", "assets/news-geography-summer-6.jpeg"] },
    { dateEn: "July 27-31, 2026", dateZh: "2026年7月27-31日", categoryEn: "Summer School", categoryZh: "暑期学校", titleEn: "Huilin Lai attends the 2026 International Summer School on Methodology of Computational Social Science", titleZh: "赖慧琳参加2026年计算社会科学方法论国际暑期学校", summaryEn: "From 27 to 31 July 2026, Huilin Lai attended the International Summer School on Methodology of Computational Social Science at Ningxia University. Through lectures, behavioural games, group projects, and discussions, she received systematic training in complex social systems, agent-based modelling, NetLogo, spatial ABM, participatory modelling, machine learning, and CGE models.", summaryZh: "2026年7月27-31日，赖慧琳参加了在宁夏大学举办的计算社会科学方法论国际暑期学校。通过专题讲座、行为实验、小组项目和交流讨论，她系统学习了复杂社会系统、基于主体的建模、NetLogo、空间 ABM、参与式建模、机器学习和 CGE 模型等方法。", images: ["assets/news-computational-summer-1.jpeg", "assets/news-computational-summer-2.jpeg", "assets/news-computational-summer-3.jpeg", "assets/news-computational-summer-4.jpeg"] },
    { dateEn: "July 15, 2026", dateZh: "2026年7月15日", categoryEn: "Academic Lecture", categoryZh: "学术讲座", titleEn: "SESuS Lab hosts an academic lecture on evolving perspectives and reflections in conservation practice", titleZh: "课题组举办保护实践中的认知变化与思考学术讲座", summaryEn: "On 15 July 2026, SESuS Lab hosted an academic lecture by Zhiqin Zhou, Chair of the Haikou Datan Wetland Research Institute. Drawing on wetland conservation and protected-area management experience, the lecture examined restoration goals, ecological monitoring, tourism and harvesting pressures, community livelihoods, benefit-sharing, and adaptive conservation governance.", summaryZh: "2026年7月15日，课题组邀请海口畓榃湿地研究所理事长周志琴开展保护实践中的认知变化与思考学术讲座。讲座结合湿地保护和保护地管理实践，围绕修复目标、生态监测、旅游与赶海压力、社区生计和利益共享等议题展开，并探讨更加适应性、有效和包容的保护治理路径。", images: ["assets/news-conservation-lecture-1.jpeg", "assets/news-conservation-lecture-2.jpeg", "assets/news-conservation-lecture-3.jpeg", "assets/news-conservation-lecture-4.jpeg"] },
    { dateEn: "June 22-July 1, 2026", dateZh: "2026年6月22日-7月1日", categoryEn: "Field Research", categoryZh: "野外调研", titleEn: "SESuS Lab conducts field research on mangrove conservation, restoration, and integrated aquaculture across coastal China", titleZh: "课题组开展中国沿海红树林保护修复与种养耦合野外调研", summaryEn: "From 22 June to 1 July 2026, Professor Jie Su and SESuS Lab members conducted field research in Beihai, Zhanjiang, Fuding, Yueqing, and Zhoushan. The team compared mangrove restoration and integrated aquaculture practices, with attention to restoration approaches, pond-forest configurations, water and species management, coastal livelihoods, community participation, governance, and ecological value realisation.", summaryZh: "2026年6月22日至7月1日，苏婕老师与课题组成员赴北海、湛江、福鼎、乐清和舟山开展野外调研。团队通过实地考察、访谈和座谈交流，比较不同地区的红树林保护修复与种养耦合实践，重点关注修复模式、林塘空间配置、水体与物种管理、沿海生计、社区参与、项目治理和生态价值转化。", images: ["assets/news-coastal-fieldwork-1.jpeg", "assets/news-coastal-fieldwork-2.jpeg", "assets/news-coastal-fieldwork-3.jpeg", "assets/news-coastal-fieldwork-4.jpeg", "assets/news-coastal-fieldwork-5.jpeg", "assets/news-coastal-fieldwork-6.jpeg"] },
    { dateEn: "June 8-17, 2026", dateZh: "2026年6月8-17日", categoryEn: "Workshop", categoryZh: "研修班", titleEn: "Jie Su attends the IMC workshop on mangrove conservation and restoration for the Asia-Pacific region", titleZh: "苏婕参加国际红树林中心亚太地区红树林保护与修复研修班", summaryEn: "From 8 to 17 June 2026, Professor Jie Su attended the Workshop on Mangrove Conservation and Restoration for the Asia-Pacific Region in Shenzhen. The workshop, jointly organised by the International Mangrove Center and the Urban Planning and Natural Resources Bureau of Shenzhen Municipality, brought together 24 representatives from 10 economies for lectures and field activities in Shenzhen and Hainan.", summaryZh: "2026年6月8-17日，苏婕参加了在深圳举办的亚太地区红树林保护与修复研修班。研修班由国际红树林中心和深圳市规划和自然资源局共同组织，来自10个经济体的24位代表参加了在深圳和海南开展的课程学习与野外考察。", images: [] },
    { dateEn: "June 7, 2026", dateZh: "2026年6月7日", categoryEn: "Field Study", categoryZh: "实地调研", titleEn: "SESuS Lab conducts a preliminary study on community livelihoods and well-being under mangrove conservation in Zhuta Village", titleZh: "课题组赴漳江口红树林国家级自然保护区云霄县竹塔村开展红树林保护下的社区生计与福祉预调研", summaryEn: "On 7 June 2026, Professor Jie Su and SESuS Lab members conducted a preliminary field study in Zhuta Village and its surrounding mangroves, aquaculture ponds, and retired aquaculture areas. The team examined conservation, wetland restoration, community livelihoods, ecotourism potential, and the local applicability and acceptance of mangrove-aquaculture coupling models.", summaryZh: "2026年6月7日，苏婕老师与课题组成员赴云霄县竹塔村及其周边红树林、养殖塘和退养区域开展预调研。团队通过实地踏查和访谈，了解红树林保护、退养还湿、社区生计、生态旅游潜力，以及红树林—养殖耦合模式的本地适用性与接受意愿。", images: ["assets/news-zhuta-1.jpeg", "assets/news-zhuta-2.jpeg", "assets/news-zhuta-3.jpeg"] },
    { dateEn: "May 21-24, 2026", dateZh: "2026年5月21-24日", categoryEn: "Academic Meeting", categoryZh: "学术研讨会", titleEn: "Jie Su attends and presents at the 2026 Academic Symposium of the Mangrove Ecology Committee", titleZh: "苏婕参加中国生态学会红树林生态专业委员会2026年学术研讨会暨中国红树林保护高级研讨会并做汇报", summaryEn: "From 21 to 24 May 2026, Professor Jie Su attended and delivered a presentation at the 2026 Academic Symposium of the Mangrove Ecology Committee of the Ecological Society of China and the Advanced Seminar on Mangrove Conservation in China.", summaryZh: "2026年5月21-24日，苏婕参加了由中国生态学会红树林生态专业委员会主办、浙江海洋大学承办的中国生态学会红树林生态专业委员会2026年学术研讨会暨中国红树林保护高级研讨会，并作学术汇报。", images: [] },
    { dateEn: "May 9-10, 2026", dateZh: "2026年5月9-10日", categoryEn: "Conference", categoryZh: "学术会议", titleEn: "SESuS Lab attends the 2026 Chinese Journal of Environmental Science Youth Academic Conference", titleZh: "课题组参加2026年中国环境科学青年学术会议", summaryEn: "From 9 to 10 May 2026, Professor Jie Su, Huilin Lai, and Shouxiang Sun attended the 2026 Chinese Journal of Environmental Science Youth Academic Conference. Professor Su served as a session convener and presented on spatial optimisation simulation for mangrove restoration; Huilin Lai and Shouxiang Sun also presented research on wetland buffering under typhoon shocks and natural shoreline conservation planning.", summaryZh: "2026年5月9-10日，苏婕老师、赖慧琳和孙守祥参加了2026年中国环境科学青年学术会议。苏婕老师作为分会场召集人之一，作社会—生态耦合视角下的红树林修复空间优化模拟报告；赖慧琳和孙守祥分别汇报了台风冲击下湿地缓冲作用和基于成本—效益分析的中国自然岸线保护规划研究。", images: ["assets/news-ces-youth-conference-group.jpeg", "assets/news-ces-youth-conference-talk-1.jpeg", "assets/news-ces-youth-conference-talk-2.jpeg", "assets/news-ces-youth-conference-talk-3.jpeg"] }
  ];

  const publicationLinks = {
    "Dataset of production characteristics": "https://www.frontiersin.org/journals/sustainable-food-systems/articles/10.3389/fsufs.2025.1646381/full",
    "Pathways to sustainability or collapse": "https://doi.org/10.1016/j.ecolmodel.2025.111416",
    "Applying the Social-Ecological Systems": "https://doi.org/10.1016/j.ocecoaman.2025.107860",
    "Differentiated trajectories of ecosystem-based adaptation": "https://doi.org/10.1016/j.ocecoaman.2025.107799",
    "Differentiated characteristics, sustainability performance": "https://doi.org/10.1007/s11625-025-01703-w",
    "Meta-analysis of coastal defence options": "https://doi.org/10.1038/s41467-024-47040-5",
    "Assessing the heterogeneity of public acceptability": "https://doi.org/10.1016/j.ecolecon.2023.108126",
    "Mixed diets can meet nutrient requirements": "https://doi.org/10.1126/sciadv.adh1077",
    "A meta-analysis of the ecological and economic": "https://doi.org/10.1038/s41467-021-25388-0"
  };
  data.publications = data.publications.map((publication) => ({ ...publication, url: Object.entries(publicationLinks).find(([title]) => publication.text.includes(title))?.[1] || "" }));
})();
