(function () {
  Object.assign(window.siteContent.en, {
  "researchHeadline": "Connecting People and Nature for Coastal Sustainability",
  "researchIntro1": "Coastal ecosystems support biodiversity, livelihoods, and a wide range of economic activities. Their future depends on how conservation, restoration, and resource use are managed, particularly as climate change creates new pressures and uncertainties.",
  "researchIntro2": "Our research brings together social–ecological systems science and ecological economics to understand these connections and inform coastal management. We combine global evidence synthesis with local field research to examine how coastal systems change, assess the benefits they provide, and identify effective conservation and restoration strategies. Across these areas, we connect biodiversity conservation, climate mitigation and adaptation, economic development, and human well-being.",
  "dynamicsTitle": "Understanding coastal social–ecological dynamics",
  "dynamicsNav": "Coastal dynamics",
  "dynamics1": "We study how coastal ecosystems and human societies shape one another over time. This includes examining how land use, economic activities, and management policies affect coastal environments, and how ecological changes influence livelihoods and development. We seek to understand why coastal regions follow different trajectories and what enables them to withstand disturbance and recover.",
  "dynamics2": "At the global scale, our research has quantified the ecological and economic outcomes of mangrove restoration and identified factors that influence its effectiveness. In Xiamen Bay, we combine spatial analysis, surveys, and choice experiments to examine ecological suitability, ecosystem service values, and public preferences. These studies help align restoration planning with local environmental conditions and social priorities.",
  "dynamics3": "Building on this work, we are developing long-term ecological and socioeconomic datasets across coastal settings to investigate the drivers of change, stability, and recovery.",
  "benefitsTitle": "Assessing ecosystem benefits and sustainable use",
  "benefitsNav": "Ecosystem benefits",
  "benefits1": "Understanding coastal change also requires examining how people benefit from ecosystems and how management decisions affect those benefits. We combine ecological monitoring, ecosystem service valuation, cost-benefit analysis, and social surveys to evaluate conservation, restoration, and resource-use options. We consider both trade-offs among ecological, economic, and social outcomes and the distribution of costs and benefits across different groups.",
  "benefits2": "Our projects supported by the National Natural Science Foundation of China focus on integrated mangrove–aquaculture systems, coastal wetland ecotourism, and restoration under different management objectives. They examine sustainability outcomes, the conditions needed for implementation, and how ecological and landscape features shape visitor and resident experiences. Together, these studies explore how conservation, restoration, and sustainable use can support regional development.",
  "planningTitle": "Informing conservation planning and climate adaptation",
  "planningNav": "Planning and adaptation",
  "planning1": "We use insights into coastal dynamics and ecosystem benefits to inform decisions about where to act, which measures to use, and how management can respond to changing conditions.",
  "planning2": "Our spatial planning research identifies priority areas for mixed-species mangrove restoration by integrating ecological suitability, species diversity, landscape connectivity, and restoration costs. Our climate research compares engineered, ecosystem-based, and hybrid coastal defence approaches and evaluates their adaptation and mitigation outcomes. We have also examined climate risks across aquaculture value chains, identifying 53 adaptation options and the policy, information, and financial barriers affecting their implementation.",
  "planning3": "Future research will combine climate and socioeconomic scenarios to assess alternative conservation, restoration, and resource-use strategies. By examining their long-term benefits, risks, and feasibility, we aim to help coastal communities and decision-makers plan for sustainable development under uncertainty.",
  "relatedProjects": "Related projects",
  "relatedPublications": "Related publications",
  "allResearchProjects": "All projects →",
  "allResearchPublications": "All publications →",
  "researchContentsLabel": "Research areas",
  "publicationDetails": "Publication details →"
});
  Object.assign(window.siteContent.zh, {
  "researchHeadline": "连接人与自然，推动海岸带可持续发展",
  "researchIntro1": "海岸带生态系统维系着生物多样性，为社区生计和多种经济活动提供支撑。其未来取决于我们如何开展保护、修复与资源利用，尤其是在气候变化带来新的压力与不确定性的背景下。",
  "researchIntro2": "我们的研究融合社会—生态系统科学与生态经济学，理解人与海岸带生态系统之间的联系，并为管理决策提供依据。通过结合全球证据综合与地方实地研究，我们探究海岸带系统的变化，评估其提供的效益，识别有效的保护与修复策略。贯穿这些研究的是对生物多样性保护、气候变化减缓与适应、经济发展及人类福祉的统筹考虑。",
  "dynamicsTitle": "理解海岸带社会—生态系统动态",
  "dynamicsNav": "海岸带系统动态",
  "dynamics1": "我们研究海岸带生态系统与人类社会如何随时间相互影响，包括土地利用、经济活动与管理政策如何改变海岸带环境，以及生态变化如何影响生计与发展。我们关注不同地区为何沿着不同路径演变，以及哪些因素帮助系统抵御扰动并恢复。",
  "dynamics2": "在全球尺度，我们量化了红树林修复的生态与经济效益，并识别影响修复成效的因素。在厦门湾，我们结合空间分析、社会调查与选择实验，研究生态适宜性、生态系统服务价值及公众偏好。这些研究帮助修复规划更好地兼顾当地环境条件与社会需求。",
  "dynamics3": "在此基础上，我们正在构建不同海岸带地区的长期生态与社会经济数据集，以探究系统变化、稳定性及恢复的驱动因素。",
  "benefitsTitle": "评估生态系统效益与可持续利用",
  "benefitsNav": "生态系统效益",
  "benefits1": "理解海岸带变化，也需要了解人们如何从生态系统中获益，以及管理决策如何改变这些效益。我们结合生态监测、生态系统服务价值评估、成本—效益分析与社会调查，评估保护、修复及资源利用方案。研究既关注生态、经济和社会效益之间的权衡，也关注不同群体之间的成本与收益分配。",
  "benefits2": "我们承担的国家自然科学基金项目聚焦红树林—水产养殖耦合系统、滨海湿地生态旅游，以及不同管理目标下的生态修复。研究评估其可持续性表现与实施条件，并探究生态和景观特征如何影响游客与居民的体验。这些工作共同探索保护、修复及可持续利用如何支持区域发展。",
  "planningTitle": "支持保护规划与气候适应",
  "planningNav": "保护规划与气候适应",
  "planning1": "我们将对海岸带系统动态与生态系统效益的认识用于管理决策，研究应优先在哪里开展行动、采取哪些措施，以及如何应对不断变化的条件。",
  "planning2": "在空间规划方面，我们整合生态适宜性、物种多样性、景观连通性与修复成本，识别多物种红树林修复的优先区域。在气候研究方面，我们比较工程措施、基于生态系统的措施及其混合方案，评估其气候适应与减缓成效。我们还研究了水产养殖价值链中的气候风险，识别出53种适应措施，并分析影响其实施的政策、信息与资金障碍。",
  "planning3": "未来研究将结合气候与社会经济情景，评估不同保护、修复及资源利用策略。通过分析其长期效益、风险与可行性，我们希望帮助沿海社区与决策者在不确定性下规划可持续发展。",
  "relatedProjects": "相关项目",
  "relatedPublications": "相关论文",
  "allResearchProjects": "全部项目 →",
  "allResearchPublications": "全部成果 →",
  "researchContentsLabel": "研究领域",
  "publicationDetails": "论文详情 →"
});
})();
