(function () {
  Object.assign(window.siteContent.en, {
  "researchHeadline": "Connecting People and Nature for Coastal Sustainability",
  "researchIntro1": "Coastal regions connect land and sea and support closely linked ecological and socioeconomic processes. They sustain biodiversity, underpin regional economies, and contribute to climate mitigation and adaptation. Yet climate change and intensifying human activities are degrading coastal ecosystems and the services they provide. Understanding how these systems change, and how economic development can be coordinated with conservation and restoration, is central to coastal sustainable development.",
  "researchIntro2": "Our research focuses on the sustainability of coastal social–ecological systems. We examine interactions and feedbacks between people and coastal ecosystems to identify effective strategies and inform decisions about conservation, restoration, and sustainable use.",
  "dynamicsTitle": "Understanding coastal social–ecological system dynamics",
  "dynamicsNav": "Coastal dynamics",
  "dynamics1": "Restoration is often assessed through ecological indicators alone, leaving its economic and social outcomes less well understood. We developed a framework to evaluate ecological and economic outcomes across global mangrove restoration studies and identify factors influencing their effectiveness. This work provides a basis for examining restoration within broader social–ecological systems.",
  "dynamics2": "Building on this framework, our case studies in Xiamen Bay, Quanzhou Bay, and the Zhangjiang Estuary combine remote sensing, surveys with large samples, interviews, and choice experiments. These studies assess ecological suitability, ecosystem service values, and implications for human well-being, while examining differences in the long-term trajectories of mangrove social–ecological systems. Together, they inform restoration planning that accounts for ecological conditions, economic considerations, and social needs.",
  "dynamics3": "We are currently collecting long-term ecological data and conducting socioeconomic surveys across coastal China. This work aims to identify the drivers of system change and assess system stability and the capacity to recover from disturbance across different environmental and development contexts.",
  "benefitsTitle": "Examining coupled systems and feedback processes",
  "benefitsNav": "Coupled systems and feedbacks",
  "benefits1": "Mangrove loss and recovery are closely connected to regional development and community livelihoods. Understanding these relationships requires attention to the ecological processes, resource-use decisions, and economic activities that link mangroves and people. We apply large language models and complex network analysis to synthesise evidence on interactions and feedbacks within mangrove social–ecological systems.",
  "benefits2": "To address conflicts between mangrove conservation and aquaculture, we combine spatial analysis and field surveys to trace changes in mangrove–aquaculture systems across China and develop a typology of integrated mangrove–aquaculture (IMA) systems. Case studies in Beihai, Zhanjiang, Fuding, Cangnan, and Yueqing represent different IMA types and assess their ecological, economic, and social outcomes through long-term ecological monitoring and socioeconomic surveys.",
  "benefits3": "These data will inform system dynamics and agent-based models to identify the mechanisms and feedbacks that shape these outcomes. We pay particular attention to feedbacks and thresholds that influence whether the ecological, economic, and social benefits of restoration persist over time.",
  "planningTitle": "Optimising conservation and restoration planning",
  "planningNav": "Conservation planning",
  "planning1": "Coastal wetland restoration in China is increasingly expected to deliver multiple benefits alongside gains in restored area. However, outcomes vary across restoration approaches, locations, and designs. Planning therefore needs to consider where interventions can be implemented, which measures are appropriate, and how their effectiveness can be improved.",
  "planning2": "One strand of our research addresses these questions through cost-minimisation models that identify priority areas for shoreline conservation in China. This work examines how conservation objectives can be achieved while accounting for opportunity costs. For mangrove restoration and sustainable use, we are developing multi-objective spatial optimisation models to explore alternative allocations of restoration strategies under uncertain climate and socioeconomic conditions. The aim is to support planning that balances multiple objectives and remains responsive to future change.",
  "planning3": "Our future research will combine climate and socioeconomic scenarios to explore how coastal systems may respond to alternative conservation, restoration, and resource-use strategies. By assessing long-term benefits, risks, and implementation conditions, we aim to support planning that advances biodiversity conservation, climate resilience, and sustainable development under uncertainty.",
  "nbsTitle": "Developing nature-based solutions for coastal sustainability",
  "nbsNav": "Nature-based solutions",
  "nbs1": "Nature-based solutions use ecosystem conservation, restoration, and sustainable management to address societal challenges while benefiting biodiversity and human well-being. Our current research focuses on climate mitigation and adaptation, sustainable livelihoods, and coastal development.",
  "nbs2": "We assessed the ecological and economic outcomes of engineered, ecosystem-based, and hybrid coastal defence measures. Our meta-analysis found that soft and hybrid measures were more cost-effective than hard engineering, with benefits for risk reduction and climate mitigation that depend on the reference ecosystem and risk context. This research helps evaluate the effectiveness, benefits, and trade-offs of nature-based approaches and how they can complement engineering.",
  "nbs3": "We have also studied climate adaptation pathways across aquaculture value chains, identifying 53 adaptation options and barriers to their implementation. Drawing on this evidence, we aim to identify the conditions that enable nature-based solutions to be adopted and sustained in coastal settings.",
  "nbs4": "Our future research will evaluate the long-term benefits and trade-offs of nature-based solutions under changing climate and socioeconomic conditions, and identify the governance and financial conditions needed for their adoption and sustained effectiveness. We will use this evidence to inform how these approaches can support biodiversity conservation, climate resilience, and sustainable livelihoods.",
  "figureTitle": "Comparing coastal defence options",
  "figureAlt": "Published summary figure comparing soft, hybrid, and hard coastal defence with natural ecosystems and unvegetated systems, and hybrid measures with soft and hard measures, across wave attenuation, shoreline response, carbon storage, greenhouse gas emissions, and overall performance.",
  "figureSummary": "Figure 4 summarises the meta-analysis. Arrows show higher or lower performance relative to each comparison; colours indicate effect-size ranges. White arrows indicate no statistically clear difference, and bars indicate unavailable data. Some comparisons have few observations, so results should be interpreted in context.",
  "figureSource": "Source: Huynh et al. (2024), Nature Communications 15, 2870, Figure 4. Reproduced unchanged under CC BY 4.0.",
  "viewFigure": "View full-size figure ↗",
  "figurePaper": "Read the publication →",
  "relatedProjects": "Related projects",
  "relatedPublications": "Related publications",
  "allResearchProjects": "All projects →",
  "allResearchPublications": "All publications →",
  "researchContentsLabel": "Research areas",
  "publicationDetails": "Publication details →"
});
  Object.assign(window.siteContent.zh, {
  "researchHeadline": "连接人与自然，推动海岸带可持续发展",
  "researchIntro1": "海岸带连接陆地与海洋，承载着紧密关联的生态与社会经济过程。它维系生物多样性、支撑区域经济，并为气候变化减缓与适应作出贡献。然而，气候变化和日益加剧的人类活动正在削弱海岸带生态系统及其提供的服务。理解这些系统如何变化，以及如何协调经济发展与生态保护、修复，是推动海岸带可持续发展的关键。",
  "researchIntro2": "我们的研究聚焦海岸带社会—生态系统的可持续性，探究人与海岸带生态系统之间的相互作用和反馈，识别有效策略，为保护、修复及可持续利用提供决策依据。",
  "dynamicsTitle": "理解海岸带社会—生态系统动态",
  "dynamicsNav": "海岸带系统动态",
  "dynamics1": "生态修复往往主要通过生态指标进行评估，其经济与社会效益尚未得到充分理解。我们构建了评估框架，综合分析全球红树林修复研究中的生态与经济效益，并识别影响修复成效的因素，为在更广泛的社会—生态系统背景下研究修复提供基础。",
  "dynamics2": "在此基础上，我们在厦门湾、泉州湾和漳江口开展案例研究，结合遥感、大样本社会调查、访谈及选择实验，评估生态适宜性、生态系统服务价值及其对人类福祉的影响，同时探究红树林社会—生态系统长期演变路径的差异。这些研究为兼顾生态条件、经济因素和社会需求的修复规划提供依据。",
  "dynamics3": "目前，我们正在中国沿海地区收集长期生态数据并开展社会经济调查，旨在识别系统变化的驱动因素，评估不同环境与发展背景下的系统稳定性及其从扰动中恢复的能力。",
  "benefitsTitle": "探究耦合系统与反馈过程",
  "benefitsNav": "耦合系统与反馈",
  "benefits1": "红树林的退化与恢复同区域发展和社区生计密切相关。理解这些联系，需要关注连接红树林与人类社会的生态过程、资源利用决策及经济活动。我们运用大语言模型和复杂网络分析，综合红树林社会—生态系统相互作用与反馈的相关证据。",
  "benefits2": "为应对红树林保护与水产养殖之间的冲突，我们结合空间分析与实地调查，追踪中国红树林—养殖系统的变化，并构建红树林种养耦合（IMA）系统的类型划分。北海、湛江、福鼎、苍南和乐清的案例代表不同的 IMA 类型，通过长期生态监测与社会经济调查，评估其生态、经济和社会效益。",
  "benefits3": "这些数据将用于构建系统动力学与基于主体的模型，识别影响上述效益的机制和反馈。我们尤其关注决定修复的生态、经济及社会效益能否持续的反馈过程和阈值。",
  "planningTitle": "优化保护与修复规划",
  "planningNav": "保护与修复规划",
  "planning1": "中国滨海湿地修复越来越强调在扩大修复面积的同时实现多重效益。然而，不同修复方式、地点与设计的成效存在差异。因此，规划需要考虑在哪里实施干预、哪些措施适宜，以及如何提高措施的有效性。",
  "planning2": "我们的一项研究通过成本最小化模型识别中国岸线保护的优先区域，探讨如何在考虑保护机会成本的同时实现保护目标。针对红树林修复与可持续利用，我们正在开发多目标空间优化模型，在气候与社会经济条件不确定的背景下，探索不同修复策略的空间配置方案，为兼顾多重目标并能应对未来变化的规划提供支持。",
  "planning3": "未来研究将结合气候与社会经济情景，探究海岸带系统对不同保护、修复及资源利用策略的响应。通过评估长期效益、风险与实施条件，我们希望支持在不确定性下推进生物多样性保护、气候韧性和可持续发展的规划。",
  "nbsTitle": "发展面向海岸带可持续发展的基于自然的解决方案",
  "nbsNav": "基于自然的解决方案",
  "nbs1": "基于自然的解决方案通过生态系统保护、修复与可持续管理，在促进生物多样性和人类福祉的同时应对社会挑战。我们目前重点研究气候变化减缓与适应、可持续生计和海岸带发展。",
  "nbs2": "我们评估了工程措施、基于生态系统的措施及混合海岸防护措施的生态与经济效益。荟萃分析发现，基于生态系统的软措施和混合措施比硬工程更具成本效益，其降低风险及减缓气候变化的效益取决于参照生态系统与风险背景。这些研究帮助我们评估基于自然的措施的成效、效益与权衡，并探究它们如何与工程措施相互补充。",
  "nbs3": "我们也研究了水产养殖价值链中的气候适应路径，识别出53种适应措施及其实施障碍。在此基础上，我们希望进一步识别有助于基于自然的解决方案在海岸带被采纳并持续发挥作用的条件。",
  "nbs4": "未来研究将评估气候与社会经济条件变化背景下基于自然的解决方案的长期效益与权衡，并识别支持其采纳和持续有效实施的治理及资金条件。我们将运用这些证据，探究上述方案如何支持生物多样性保护、气候韧性和可持续生计。",
  "figureTitle": "比较不同海岸防护方案",
  "figureAlt": "已发表论文的总结图，比较软措施、混合措施和硬工程相对于自然生态系统及无植被系统的表现，并比较混合措施与软措施、硬工程在消浪、岸线响应、碳储量、温室气体排放及综合表现方面的差异。",
  "figureSummary": "图4总结了荟萃分析结果。箭头表示相对于各参照对象更高或更低的表现，颜色表示效应量范围；白色箭头表示差异在统计上不明确，横杠表示缺少数据。部分比较的观测数较少，需结合具体背景解读。",
  "figureSource": "来源：Huynh 等（2024），Nature Communications 15, 2870，图4。依据 CC BY 4.0 授权转载，原图未作修改。",
  "viewFigure": "查看完整原图 ↗",
  "figurePaper": "阅读相关论文 →",
  "relatedProjects": "相关项目",
  "relatedPublications": "相关论文",
  "allResearchProjects": "全部项目 →",
  "allResearchPublications": "全部成果 →",
  "researchContentsLabel": "研究领域",
  "publicationDetails": "论文详情 →"
});
})();
